name: Package Application with PyInstaller

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Package Application Linux
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build
      run: |
          pyinstaller bcml.spec
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: bcml-linux
        path: dist/Battle Cats Mod Loader
    
