name: Package Application with Pyinstaller

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: Battle Cats Mod Loader
        path: dist/linux

  build_windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: Battle Cats Mod Loader
        path: dist/windows
