name: Package Application with PyInstaller

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Package Application Linux
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build
      run: |
          pyinstaller bcml.spec
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: bcml-linux
        path: dist/bcml
    
